import { useRef } from 'react'
import { FileText, Download, AlertTriangle, CheckCircle, Activity, ChevronRight } from 'lucide-react'
import html2pdf from 'html2pdf.js'

function ReportViewer({ report, validation, onChat }) {
  const reportRef = useRef()

  const handleDownloadPdf = () => {
    const element = reportRef.current
    const opt = {
      margin: 10,
      filename: 'OmniMed_Clinical_Report.pdf',
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    }
    html2pdf().from(element).set(opt).save()
  }

  if (!report) return null

  const getRiskColor = (level) => {
    switch(level?.toLowerCase()) {
      case 'high': return 'var(--danger)'
      case 'medium': return 'var(--warning)'
      case 'low': return 'var(--success)'
      default: return 'var(--text-secondary)'
    }
  }

  return (
    <div className="glass-panel animate-fade-in" style={{ maxWidth: '900px', margin: '0 auto', padding: '0' }}>
      
      {/* Header Actions */}
      <div style={{ display: 'flex', justifyContent: 'space-between', padding: '24px', borderBottom: '1px solid var(--border-color)' }}>
        <h2 style={{ display: 'flex', alignItems: 'center', gap: '12px', margin: 0 }}>
          <FileText color="var(--accent-primary)" /> Analysis Complete
        </h2>
        <div style={{ display: 'flex', gap: '12px' }}>
          <button className="btn-secondary" onClick={handleDownloadPdf}>
            <Download size={20} /> Download PDF
          </button>
          <button className="btn-primary" onClick={onChat}>
            Discuss Results <ChevronRight size={20} />
          </button>
        </div>
      </div>

      {/* Report Content to be PDF'd */}
      <div ref={reportRef} style={{ padding: '40px', background: 'var(--bg-primary)', color: 'var(--text-primary)' }}>
        
        <div style={{ textAlign: 'center', marginBottom: '40px', borderBottom: '2px solid var(--border-color)', paddingBottom: '24px' }}>
          <h1 style={{ marginBottom: '8px', color: 'var(--accent-primary)' }}>OmniMed Clinical Report</h1>
          <p style={{ color: 'var(--text-secondary)' }}>Generated by AI - For informational purposes only</p>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px', marginBottom: '40px' }}>
          <div style={{ background: 'var(--bg-secondary)', padding: '20px', borderRadius: '12px', border: '1px solid var(--border-color)' }}>
            <h3 style={{ marginBottom: '12px', color: 'var(--text-secondary)' }}>Overview</h3>
            <p><strong>Scan/Doc Type:</strong> {report.image_type || 'Unknown'}</p>
            <p><strong>Region/System:</strong> {report.body_region || 'Unknown'}</p>
          </div>
          
          <div style={{ 
            background: 'var(--bg-secondary)', 
            padding: '20px', 
            borderRadius: '12px', 
            border: `2px solid ${getRiskColor(report.cancer_risk?.risk_level)}`,
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            textAlign: 'center'
          }}>
            <h3 style={{ color: getRiskColor(report.cancer_risk?.risk_level), marginBottom: '8px' }}>
              Risk Assessment: {report.cancer_risk?.risk_level || 'N/A'}
            </h3>
            {report.cancer_risk?.suspected_type && (
              <p><strong>Suspected:</strong> {report.cancer_risk.suspected_type}</p>
            )}
            <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginTop: '8px' }}>
              {report.cancer_risk?.reasoning || 'No reasoning provided.'}
            </p>
          </div>
        </div>

        <div style={{ marginBottom: '40px' }}>
          <h3 style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '8px', marginBottom: '16px' }}>Clinical Findings</h3>
          <ul style={{ paddingLeft: '20px', lineHeight: '1.8' }}>
            {report.findings?.map((finding, idx) => (
              <li key={idx}>{finding}</li>
            )) || <li>No findings extracted.</li>}
          </ul>
        </div>

        {report.conditions && report.conditions.length > 0 && (
          <div style={{ marginBottom: '40px' }}>
            <h3 style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '8px', marginBottom: '16px' }}>Identified Conditions</h3>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '12px' }}>
              {report.conditions.map((cond, idx) => (
                <span key={idx} style={{ background: 'rgba(37, 99, 235, 0.1)', color: 'var(--accent-primary)', padding: '6px 16px', borderRadius: '20px', fontSize: '0.9rem', fontWeight: 'bold' }}>
                  {cond}
                </span>
              ))}
            </div>
          </div>
        )}

        <div style={{ marginBottom: '40px' }}>
          <h3 style={{ borderBottom: '1px solid var(--border-color)', paddingBottom: '8px', marginBottom: '16px' }}>Recommended Next Steps</h3>
          <ul style={{ paddingLeft: '20px', lineHeight: '1.8' }}>
            {report.next_steps?.map((step, idx) => (
              <li key={idx}>{step}</li>
            )) || <li>Consult a healthcare professional.</li>}
          </ul>
        </div>

        {validation && (
          <div style={{ 
            background: 'var(--bg-secondary)', 
            padding: '16px', 
            borderRadius: '8px', 
            display: 'flex', 
            alignItems: 'flex-start', 
            gap: '12px',
            borderLeft: '4px solid var(--success)'
          }}>
            <CheckCircle color="var(--success)" size={24} style={{ flexShrink: 0 }} />
            <div>
              <h4 style={{ margin: 0, marginBottom: '4px' }}>AI Validation Passed (Score: {validation.reliability_score || 0}/100)</h4>
              <p style={{ margin: 0, fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
                {validation.validation_notes || 'The report has been checked for AI hallucinations and logical consistency.'}
              </p>
            </div>
          </div>
        )}
        
        <div style={{ marginTop: '40px', paddingTop: '20px', borderTop: '1px solid var(--border-color)', textAlign: 'center', fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
          <AlertTriangle size={16} style={{ display: 'inline', verticalAlign: 'middle', marginRight: '4px' }} />
          This report is generated by Artificial Intelligence and does not constitute medical advice. Always consult a licensed healthcare provider.
        </div>
      </div>
    </div>
  )
}

export default ReportViewer
